name: CI/CD Pipeline

on:
  push:
    branches: [ main, lab3 ]
  pull_request:
    branches: [ main, lab3 ]

jobs:
  # ЕТАП 1: Continuous Integration (Аналіз та Тести)
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r mywebapp/requirements.txt

      - name: Lint with flake8 (Static Analysis)
        run: flake8 mywebapp/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Run Tests with Coverage
        run: |
          cd mywebapp
          export PYTHONPATH=.
          pytest --cov=./ --cov-report=xml

# ЕТАП 2: Continuous Delivery (Розгортання на self-hosted раннері)
  cd:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/lab3'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          # 1. Заходимо в папку з лабою, щоб Docker Compose правильно підтягнув конфіг Nginx
          cd mywebapp
          
          # 2. Запускаємо збірку та піднімаємо контейнери
          sudo docker compose up -d --build

      - name: Run Post-Deployment Verification
        run: |
          # 3. verify.sh лежить у корені, тому запускаємо його прямо звідси без переходів
          chmod +x ./verify.sh
          ./verify.sh
